services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #
    OpenDxp\Bundle\WordExportBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpWordExportBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    OpenDxp\Bundle\WordExportBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]