services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #

    OpenDxp\Bundle\SeoBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpSeoBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    OpenDxp\Bundle\SeoBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']