doctrine:
    orm:
        mappings:
            OpenDxpGenericExecutionEngineBundle:
                type: attribute
                is_bundle: true
                dir: src/Entity
                prefix: OpenDxp\Bundle\GenericExecutionEngineBundle\Entity
                alias: OpenDxpGenericExecutionEngineBundle