services:
    _defaults:
        autowire: true
        autoconfigure: true

    # RENDERERS

    OpenDxp\Templating\Renderer\ActionRenderer:
        arguments:
            $httpKernelRuntime: '@twig.runtime.httpkernel'

    OpenDxp\Templating\Renderer\IncludeRenderer: ~

    OpenDxp\Templating\Renderer\EditableRenderer:
        public: true
        arguments:
            $editableLoader: '@OpenDxp\Model\Document\Editable\Loader\EditableLoader'
        calls:
            - [setLogger, ['@logger']]

    # NAVIGATION

    # renderer locator collecting all registered renderers
    opendxp.templating.navigation.renderer_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments: [[]]

    OpenDxp\Navigation\Builder: ~

    OpenDxp\Navigation\Renderer\Menu:
        tags:
            - { name: opendxp.navigation.renderer, alias: menu }

    OpenDxp\Navigation\Renderer\Breadcrumbs:
        tags:
            - { name: opendxp.navigation.renderer, alias: breadcrumbs }

    opendxp.templating:
        alias: 'twig'
        public: true
