<?php
declare(strict_types=1);

/**
 * OpenDXP
 *
 * This source file is licensed under the GNU General Public License version 3 (GPLv3).
 *
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (https://pimcore.com)
 * @copyright  Modification Copyright (c) OpenDXP (https://www.opendxp.io)
 * @license    https://www.gnu.org/licenses/gpl-3.0.html  GNU General Public License version 3 (GPLv3)
 */

return [
    'OpenDxp\\Model\\Asset' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Archive' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Audio' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Document' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Folder' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Image' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Image\\Thumbnail\\Config' => 'OpenDxp\\Model\\Asset\\Image\\Thumbnail\\Config\\Dao',
    'OpenDxp\\Model\\Asset\\Image\\Thumbnail\\Config\\Listing' => 'OpenDxp\\Model\\Asset\\Image\\Thumbnail\\Config\\Listing\\Dao',
    'OpenDxp\\Model\\Asset\\Listing' => 'OpenDxp\\Model\\Asset\\Listing\\Dao',
    'OpenDxp\\Model\\Asset\\Service' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Text' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Unknown' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Video' => 'OpenDxp\\Model\\Asset\\Dao',
    'OpenDxp\\Model\\Asset\\Video\\Thumbnail\\Config' => 'OpenDxp\\Model\\Asset\\Video\\Thumbnail\\Config\\Dao',
    'OpenDxp\\Model\\Asset\\Video\\Thumbnail\\Config\\Listing' => 'OpenDxp\\Model\\Asset\\Video\\Thumbnail\\Config\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject' => 'OpenDxp\\Model\\DataObject\\AbstractObject\\Dao',
    'OpenDxp\\Model\\DataObject\\ClassDefinition' => 'OpenDxp\\Model\\DataObject\\ClassDefinition\\Dao',
    'OpenDxp\\Model\\DataObject\\ClassDefinition\\CustomLayout' => 'OpenDxp\\Model\\DataObject\\ClassDefinition\\CustomLayout\\Dao',
    'OpenDxp\\Model\\DataObject\\ClassDefinition\\CustomLayout\\Listing' => 'OpenDxp\\Model\\DataObject\\ClassDefinition\\CustomLayout\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\ClassDefinition\\Listing' => 'OpenDxp\\Model\\DataObject\\ClassDefinition\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionConfig' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionConfig\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionConfig\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionConfig\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionGroupRelation' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionGroupRelation\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionGroupRelation\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\CollectionGroupRelation\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\GroupConfig' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\GroupConfig\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\GroupConfig\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\GroupConfig\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyConfig' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyConfig\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyConfig\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyConfig\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyGroupRelation' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyGroupRelation\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyGroupRelation\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\KeyGroupRelation\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\StoreConfig' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\StoreConfig\\Dao',
    'OpenDxp\\Model\\DataObject\\Classificationstore\\StoreConfig\\Listing' => 'OpenDxp\\Model\\DataObject\\Classificationstore\\StoreConfig\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Concrete' => 'OpenDxp\\Model\\DataObject\\Concrete\\Dao',
    'OpenDxp\\Model\\DataObject\\Data\\ElementMetadata' => 'OpenDxp\\Model\\DataObject\\Data\\ElementMetadata\\Dao',
    'OpenDxp\\Model\\DataObject\\Data\\ObjectMetadata' => 'OpenDxp\\Model\\DataObject\\Data\\ObjectMetadata\\Dao',
    'OpenDxp\\Model\\DataObject\\Fieldcollection' => 'OpenDxp\\Model\\DataObject\\Fieldcollection\\Dao',
    'OpenDxp\\Model\\DataObject\\Fieldcollection\\Definition' => 'OpenDxp\\Model\\DataObject\\Fieldcollection\\Definition\\Dao',
    'OpenDxp\\Model\\DataObject\\Folder' => 'OpenDxp\\Model\\DataObject\\Folder\\Dao',
    'OpenDxp\\Model\\DataObject\\Listing' => 'OpenDxp\\Model\\DataObject\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Localizedfield' => 'OpenDxp\\Model\\DataObject\\Localizedfield\\Dao',
    'OpenDxp\\Model\\DataObject\\Objectbrick' => 'OpenDxp\\Model\\DataObject\\Objectbrick\\Dao',
    'OpenDxp\\Model\\DataObject\\Objectbrick\\Definition' => 'OpenDxp\\Model\\DataObject\\Objectbrick\\Definition\\Dao',
    'OpenDxp\\Model\\DataObject\\QuantityValue\\Unit' => 'OpenDxp\\Model\\DataObject\\QuantityValue\\Unit\\Dao',
    'OpenDxp\\Model\\DataObject\\QuantityValue\\Unit\\Listing' => 'OpenDxp\\Model\\DataObject\\QuantityValue\\Unit\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\SelectOptions\\Config' => 'OpenDxp\\Model\\DataObject\\SelectOptions\\Config\\Dao',
    'OpenDxp\\Model\\DataObject\\SelectOptions\\Config\\Listing' => 'OpenDxp\\Model\\DataObject\\SelectOptions\\Config\\Listing\\Dao',
    'OpenDxp\\Model\\DataObject\\Service' => 'OpenDxp\\Model\\Element\\Dao',
    'OpenDxp\\Model\\Dependency' => 'OpenDxp\\Model\\Dependency\\Dao',
    'OpenDxp\\Model\\Document' => 'OpenDxp\\Model\\Document\\Dao',
    'OpenDxp\\Model\\Document\\DocType' => 'OpenDxp\\Model\\Document\\DocType\\Dao',
    'OpenDxp\\Model\\Document\\DocType\\Listing' => 'OpenDxp\\Model\\Document\\DocType\\Listing\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Area' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Areablock' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Block' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Checkbox' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Date' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Embed' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Image' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Input' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Link' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Multiselect' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Numeric' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Pdf' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Relation' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Relations' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Renderlet' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Scheduledblock' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Select' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Snippet' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Table' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Textarea' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Video' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Editable\\Wysiwyg' => 'OpenDxp\\Model\\Document\\Editable\\Dao',
    'OpenDxp\\Model\\Document\\Email' => 'OpenDxp\\Model\\Document\\Email\\Dao',
    'OpenDxp\\Model\\Document\\Folder' => 'OpenDxp\\Model\\Document\\Folder\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Email' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Folder' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Hardlink' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Link' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Page' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Printcontainer' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Printpage' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Hardlink\\Wrapper\\Snippet' => 'OpenDxp\\Model\\Document\\Hardlink\\Dao',
    'OpenDxp\\Model\\Document\\Link' => 'OpenDxp\\Model\\Document\\Link\\Dao',
    'OpenDxp\\Model\\Document\\Listing' => 'OpenDxp\\Model\\Document\\Listing\\Dao',
    'OpenDxp\\Model\\Document\\Page' => 'OpenDxp\\Model\\Document\\Page\\Dao',
    'OpenDxp\\Model\\Document\\Printcontainer' => 'OpenDxp\\Model\\Document\\Printcontainer\\Dao',
    'OpenDxp\\Model\\Document\\Printpage' => 'OpenDxp\\Model\\Document\\Printpage\\Dao',
    'OpenDxp\\Model\\Document\\Service' => 'OpenDxp\\Model\\Document\\Service\\Dao',
    'OpenDxp\\Model\\Document\\Snippet' => 'OpenDxp\\Model\\Document\\Snippet\\Dao',
    'OpenDxp\\Model\\Element\\Editlock' => 'OpenDxp\\Model\\Element\\Editlock\\Dao',
    'OpenDxp\\Model\\Element\\Note' => 'OpenDxp\\Model\\Element\\Note\\Dao',
    'OpenDxp\\Model\\Element\\Note\\Listing' => 'OpenDxp\\Model\\Element\\Note\\Listing\\Dao',
    'OpenDxp\\Model\\Element\\Recyclebin' => 'OpenDxp\\Model\\Element\\Recyclebin\\Dao',
    'OpenDxp\\Model\\Element\\Recyclebin\\Item' => 'OpenDxp\\Model\\Element\\Recyclebin\\Item\\Dao',
    'OpenDxp\\Model\\Element\\Recyclebin\\Item\\Listing' => 'OpenDxp\\Model\\Element\\Recyclebin\\Item\\Listing\\Dao',
    'OpenDxp\\Model\\Element\\Service' => 'OpenDxp\\Model\\Element\\Dao',
    'OpenDxp\\Model\\Element\\Tag' => 'OpenDxp\\Model\\Element\\Tag\\Dao',
    'OpenDxp\\Model\\Element\\Tag\\Listing' => 'OpenDxp\\Model\\Element\\Tag\\Listing\\Dao',
    'OpenDxp\\Model\\Element\\WorkflowState' => 'OpenDxp\\Model\\Element\\WorkflowState\\Dao',
    'OpenDxp\\Model\\Element\\WorkflowState\\Listing' => 'OpenDxp\\Model\\Element\\WorkflowState\\Listing\\Dao',
    'OpenDxp\\Model\\Glossary' => 'OpenDxp\\Model\\Glossary\\Dao',
    'OpenDxp\\Model\\Glossary\\Listing' => 'OpenDxp\\Model\\Glossary\\Listing\\Dao',
    'OpenDxp\\Model\\Metadata\\Predefined' => 'OpenDxp\\Model\\Metadata\\Predefined\\Dao',
    'OpenDxp\\Model\\Metadata\\Predefined\\Listing' => 'OpenDxp\\Model\\Metadata\\Predefined\\Listing\\Dao',
    'OpenDxp\\Model\\Notification' => 'OpenDxp\\Model\\Notification\\Dao',
    'OpenDxp\\Model\\Notification\\Listing' => 'OpenDxp\\Model\\Notification\\Listing\\Dao',
    'OpenDxp\\Model\\Property' => 'OpenDxp\\Model\\Property\\Dao',
    'OpenDxp\\Model\\Property\\Predefined' => 'OpenDxp\\Model\\Property\\Predefined\\Dao',
    'OpenDxp\\Model\\Property\\Predefined\\Listing' => 'OpenDxp\\Model\\Property\\Predefined\\Listing\\Dao',
    'OpenDxp\\Model\\Redirect' => 'OpenDxp\\Model\\Redirect\\Dao',
    'OpenDxp\\Model\\Redirect\\Listing' => 'OpenDxp\\Model\\Redirect\\Listing\\Dao',
    'OpenDxp\\Model\\Schedule\\Task' => 'OpenDxp\\Model\\Schedule\\Task\\Dao',
    'OpenDxp\\Model\\Schedule\\Task\\Listing' => 'OpenDxp\\Model\\Schedule\\Task\\Listing\\Dao',
    'OpenDxp\\Model\\Search\\Backend\\Data' => 'OpenDxp\\Model\\Search\\Backend\\Data\\Dao',
    'OpenDxp\\Model\\Search\\Backend\\Data\\Listing' => 'OpenDxp\\Model\\Search\\Backend\\Data\\Listing\\Dao',
    'OpenDxp\\Model\\Site' => 'OpenDxp\\Model\\Site\\Dao',
    'OpenDxp\\Model\\Site\\Listing' => 'OpenDxp\\Model\\Site\\Listing\\Dao',
    'OpenDxp\\Model\\Staticroute' => 'OpenDxp\\Model\\Staticroute\\Dao',
    'OpenDxp\\Model\\Staticroute\\Listing' => 'OpenDxp\\Model\\Staticroute\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\CustomReport\\Config' => 'OpenDxp\\Model\\Tool\\CustomReport\\Config\\Dao',
    'OpenDxp\\Model\\Tool\\CustomReport\\Config\\Listing' => 'OpenDxp\\Model\\Tool\\CustomReport\\Config\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\Email\\Blocklist' => 'OpenDxp\\Model\\Tool\\Email\\Blocklist\\Dao',
    'OpenDxp\\Model\\Tool\\Email\\Blocklist\\Listing' => 'OpenDxp\\Model\\Tool\\Email\\Blocklist\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\Email\\Log' => 'OpenDxp\\Model\\Tool\\Email\\Log\\Dao',
    'OpenDxp\\Model\\Tool\\Email\\Log\\Listing' => 'OpenDxp\\Model\\Tool\\Email\\Log\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\SettingsStore' => 'OpenDxp\\Model\\Tool\\SettingsStore\\Dao',
    'OpenDxp\\Model\\Tool\\Targeting\\Rule' => 'OpenDxp\\Model\\Tool\\Targeting\\Rule\\Dao',
    'OpenDxp\\Model\\Tool\\Targeting\\Rule\\Listing' => 'OpenDxp\\Model\\Tool\\Targeting\\Rule\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\Targeting\\TargetGroup' => 'OpenDxp\\Model\\Tool\\Targeting\\TargetGroup\\Dao',
    'OpenDxp\\Model\\Tool\\Targeting\\TargetGroup\\Listing' => 'OpenDxp\\Model\\Tool\\Targeting\\TargetGroup\\Listing\\Dao',
    'OpenDxp\\Model\\Tool\\TmpStore' => 'OpenDxp\\Model\\Tool\\TmpStore\\Dao',
    'OpenDxp\\Model\\Translation' => 'OpenDxp\\Model\\Translation\\Dao',
    'OpenDxp\\Model\\Translation\\Listing' => 'OpenDxp\\Model\\Translation\\Listing\\Dao',
    'OpenDxp\\Model\\User' => 'OpenDxp\\Model\\User\\Dao',
    'OpenDxp\\Model\\User\\AbstractUser' => 'OpenDxp\\Model\\User\\AbstractUser\\Dao',
    'OpenDxp\\Model\\User\\Folder' => 'OpenDxp\\Model\\User\\Dao',
    'OpenDxp\\Model\\User\\Listing' => 'OpenDxp\\Model\\User\\Listing\\Dao',
    'OpenDxp\\Model\\User\\Permission\\Definition' => 'OpenDxp\\Model\\User\\Permission\\Definition\\Dao',
    'OpenDxp\\Model\\User\\Permission\\Definition\\Listing' => 'OpenDxp\\Model\\User\\Permission\\Definition\\Listing\\Dao',
    'OpenDxp\\Model\\User\\Role' => 'OpenDxp\\Model\\User\\Role\\Dao',
    'OpenDxp\\Model\\User\\Role\\Folder' => 'OpenDxp\\Model\\User\\Role\\Folder\\Dao',
    'OpenDxp\\Model\\User\\Role\\Listing' => 'OpenDxp\\Model\\User\\Role\\Listing\\Dao',
    'OpenDxp\\Model\\User\\UserRole' => 'OpenDxp\\Model\\User\\UserRole\\Dao',
    'OpenDxp\\Model\\User\\UserRole\\Folder' => 'OpenDxp\\Model\\User\\UserRole\\Dao',
    'OpenDxp\\Model\\User\\Workspace\\Asset' => 'OpenDxp\\Model\\User\\Workspace\\Dao',
    'OpenDxp\\Model\\User\\Workspace\\DataObject' => 'OpenDxp\\Model\\User\\Workspace\\Dao',
    'OpenDxp\\Model\\User\\Workspace\\Document' => 'OpenDxp\\Model\\User\\Workspace\\Dao',
    'OpenDxp\\Model\\Version' => 'OpenDxp\\Model\\Version\\Dao',
    'OpenDxp\\Model\\Version\\Listing' => 'OpenDxp\\Model\\Version\\Listing\\Dao',
    'OpenDxp\\Model\\WebsiteSetting' => 'OpenDxp\\Model\\WebsiteSetting\\Dao',
    'OpenDxp\\Model\\WebsiteSetting\\Listing' => 'OpenDxp\\Model\\WebsiteSetting\\Listing\\Dao',
];
