services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #

    OpenDxp\Bundle\TinymceBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpTinymceBundle')"

