services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #

    OpenDxp\Bundle\StaticRoutesBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpStaticRoutesBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    OpenDxp\Bundle\StaticRoutesBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    # dedicated router for static routes
    OpenDxp\Bundle\StaticRoutesBundle\Routing\Staticroute\Router:
        arguments:
            $context: '@router.request_context'
        calls:
            - [ setLocaleParams, [ '%opendxp.routing.static.locale_params%' ] ]
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: router, priority: 100 }
            - { name: monolog.logger, channel: routing }